name: Upload S3
description: 'Upload directory to S3'
author: 'Adam L'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  aws_key_id:
    description: 'aws key id'
    required: true
  aws_secret_access_key:
    description: 'aws secret access key'
    required: true
  aws_bucket:
    description: 'aws bucket name'
    required: true
  source_dir:
    required: true
    description: 'directory to upload'
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Run main.py s3 upload
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install boto3
        export AWS_PUBLIC_KEY=${{inputs.aws_key_id}}
        export AWS_SECRET_KEY=${{inputs.aws_secret_access_key}}
        export BUCKET_NAME=${{inputs.aws_bucket}}
        export SOURCE_DIR=${{inputs.source_dir}}
        python main.py
  
